FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY ./ ./
# Restore as distinct layers
RUN dotnet restore
# Install dotnet ef CLI Tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
# Build and create a database migration
WORKDIR /App
RUN dotnet ef migrations add Setup
WORKDIR /App
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "Backend.dll"] 
